version: '3.3'
services:
  app:
    image: ${DOCKER_HUB_USERNAME}/node_app:${DOCKER_TAG:-dev}
    container_name: ${CONTAINER_NAME:-node_app}
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - MONGODB_URL=mongodb://mongodb:27017/${CONTAINER_NAME:-node_app}
    ports:
      - "${APP_PORT:-4000}:4000"
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo
    container_name: ${CONTAINER_NAME:-node_app}_mongodb
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis
    container_name: ${CONTAINER_NAME:-node_app}_redis

volumes:
  mongodb_data:
    driver: local
