version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: node_app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=dev
      - MONGODB_URL=mongodb://mongodb:27017/mydatabase
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: ["pm2-runtime", "start", "ecosystem.config.js"]
    depends_on:
      - mongodb
      - redis

volumes:
  mongodb_data:
