version: '3.8'
services:
  app:
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    ports:
      - "${APP_PORT:-4000}:4000"

  mongodb:
    ports:
      - "${MONGO_PORT:-27017}:27017"

  redis:
    ports:
      - "${REDIS_PORT:-6379}:6379"