name: Deploy to Linode using Linode CLI

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Linode CLI
        run: |
          pip install linode-cli

      - name: Verify Linode CLI Installation
        run: |
          linode-cli --version

      - name: Configure and Test Linode CLI
        env:
          LINODE_CLI_TOKEN: ${{ secrets.LINODE_CLI_TOKEN }}
        run: |
          export LINODE_CLI_TOKEN
          linode-cli --no-defaults linodes list || echo "Failed to list Linodes"

      - name: Update Linode Instance
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true)
        env:
          LINODE_CLI_TOKEN: ${{ secrets.LINODE_CLI_TOKEN }}
          LINODE_INSTANCE_ID: ${{ secrets.LINODE_INSTANCE_ID }}
        run: |
          NEW_LABEL="UpdatedDevAppInstance-$(date +%Y%m%d-%H%M%S)"
          echo "Updating Linode instance with label: $NEW_LABEL"
          linode-cli --no-defaults linodes update $LINODE_INSTANCE_ID --label "$NEW_LABEL" || echo "Failed to update Linode label"

      - name: Deploy to Linode
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true)
        env:
          LINODE_CLI_TOKEN: ${{ secrets.LINODE_CLI_TOKEN }}
          LINODE_INSTANCE_ID: ${{ secrets.LINODE_INSTANCE_ID }}
        run: |
          echo "Starting deployment to Linode instance $LINODE_INSTANCE_ID"
          linode-cli --no-defaults linodes ssh $LINODE_INSTANCE_ID "cd ~/node_app && \
            git pull origin dev && \
            docker-compose -f docker-compose.yml -f docker-compose.dev.yml down && \
            docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d" || echo "Deployment failed"

      - name: Verify Deployment
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true)
        env:
          LINODE_CLI_TOKEN: ${{ secrets.LINODE_CLI_TOKEN }}
          LINODE_INSTANCE_ID: ${{ secrets.LINODE_INSTANCE_ID }}
        run: |
          echo "Verifying deployment"
          linode-cli --no-defaults linodes ssh $LINODE_INSTANCE_ID "docker ps" || echo "Failed to verify deployment"
