name: Deploy to Linode

on:
  push:
    branches: [ main, dev ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/node_app:${{ github.ref_name }}
  
    - name: Deploy to Linode (Dev) - SSH
      if: github.ref == 'refs/heads/dev'
      uses: appleboy/ssh-action@v0.1.7 # Use a specific version instead of 'dev'
      with:
        host: ${{ secrets.LINODE_DEV_HOST }}
        username: ${{ secrets.LINODE_USER }}
        password: ${{ secrets.LINODE_PASSWORD }}
        port: ${{ secrets.LINODE_PORT }}
        script: |
          scp docker-compose.yml docker-compose.dev.yml ecosystem.config.js ${{ secrets.LINODE_USER }}@${{ secrets.LINODE_DEV_HOST }}:~/node_app/
          ssh ${{ secrets.LINODE_USER }}@${{ secrets.LINODE_DEV_HOST }} << EOF
            cd ~/node_app
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/node_app:dev
            docker-compose -f docker-compose.yml -f docker-compose.dev.yml down
            docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d
          EOF

    - name: Deploy to Linode (Production) - SSH
      if: github.ref == 'refs/heads/main'
      uses: appleboy/ssh-action@v0.1.7 # Use a specific version instead of 'dev'
      with:
        host: ${{ secrets.LINODE_PROD_HOST }}
        username: ${{ secrets.LINODE_USER }}
        password: ${{ secrets.LINODE_PASSWORD }}
        port: ${{ secrets.LINODE_PORT }}
        script: |
          scp docker-compose.yml docker-compose.prod.yml ecosystem.config.js ${{ secrets.LINODE_USER }}@${{ secrets.LINODE_PROD_HOST }}:~/node_app/
          ssh ${{ secrets.LINODE_USER }}@${{ secrets.LINODE_PROD_HOST }} << EOF
            cd ~/node_app
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/node_app:main
            docker-compose -f docker-compose.yml -f docker-compose.prod.yml down
            docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
          EOF
