name: Deploy to Linode

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.LINODE_HOST }}
          username: ${{ secrets.LINODE_USER }}
          key: ${{ secrets.LINODE_SSH_PRIVATE_KEY }}
          port: ${{ secrets.LINODE_PORT }}

      - name: Add known hosts
        run: |
          mkdir -p ~/.ssh
          echo "$LINODE_KNOWN_HOSTS" > ~/.ssh/known_hosts
        env:
          LINODE_KNOWN_HOSTS: ${{ secrets.LINODE_KNOWN_HOSTS }}

      - name: Copy files to server
        run: |
          scp docker-compose.yml docker-compose.dev.yml ecosystem.config.js $LINODE_USER@$LINODE_HOST:~/node_app/
        env:
          LINODE_USER: ${{ secrets.LINODE_USER }}
          LINODE_HOST: ${{ secrets.LINODE_HOST }}

      - name: Deploy application
        run: |
          ssh $LINODE_USER@$LINODE_HOST << EOF
            cd ~/node_app
            docker pull ***/node_app:dev
            docker-compose -f docker-compose.yml -f docker-compose.dev.yml down
            docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d
          EOF
        env:
          LINODE_USER: ${{ secrets.LINODE_USER }}
          LINODE_HOST: ${{ secrets.LINODE_HOST }}
